hydra:
  run:
    dir: logs/sbn_sngan_32
logging:
  log_dir: logs/sbn_sngan_32
  experiment_name: sbn_sngan_32
dataset:
  dataset_dir: datasets
  dataset_name: cifar10
model:
  GAN:
    nz: 128
    ngf: 256
    ndf: 128
    loss_type: hinge # "hinge", "ns", "gan", "wasserstein"
    num_classes: 0
optimizer:
  lrG: 0.0002
  lrD: 0.0002
  beta1: 0.0
  beta2: 0.9
training:
  num_workers: 4
  batch_size: 64
  n_dis: 5
  num_steps: 100000
  is_amp: true
  opt_level: O1
metrics:
  fid:
    num_real_samples: 50000
    num_fake_samples: 50000
    evaluate_step: 100000
  inception_score:
    num_samples: 50000
    evaluate_step: 100000
  kid:
    num_subsets: 50
    subset_size: 1000
    evaluate_step: 100000