version: "3"
services:
  stargan:
    image: stargan.dev
    build:
      context: .
      dockerfile: Dockerfile.cpu
      args:
        - PYTHON_VERSION=3.8
    volumes:
      - ../:/home/src
    ports:
      - "8888:8888"
    tty: true
  tensorboard:
    image: stargan.tensorboard
    build:
      context: .
      dockerfile: Dockerfile.tensorboard
    volumes:
      - ../stargan/logs:/logs
    working_dir: /logs
    ports:
      - "6006:6006"
    environment:
      reload_interval: 2
      log_dir: /logs
    command: tensorboard --logdir=/logs --host=0.0.0.0
